spring:
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.mailgun.org
    username: chirp@sandbox9c631478e492462da118b1adfbc80b26.mailgun.org

jwt:
  expiration-minutes: 15


nginx:
  require-proxy: false

chirp:
  rate-limiting:
    ip:
      apply-limit: false