spring:
  application:
    name: chirp



  data :
    redis:
      port: 12610
      connect-timeout: 5000ms
      host: "redis-12610.c277.us-east-1-3.ec2.cloud.redislabs.com"
      password: ${REDIS_PASSWORD}
      username: "default"
      timeout: 2000ms

  datasource:
    url: jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres
    username: postgres.inbgthrrpyghufkikqov
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      validation-timeout: 5000
      pool-name: SpringBootHikaricp
      data-source-properties:
        prepareThreshold: 5
        preparedStatementCacheQueries: 256
        preparedStatementCacheSizeMib: 5
        tcpKeepAlive: true
        socketTimeout: 30
        connectTimeout: 10
  jpa:
    properties:
      hibernate:
       # dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  mail:
    port: 587
    password: ${MAILGUN_PASSWORD}
    properties:
      mail:
        SMTP:
          auth: true
          STARTTLS:
            enable: true

  rabbitmq:
    host: "raccoon.lmq.cloudamqp.com"
    port: 5672
    password: "${RABBITMQ_PASSWORD}"
    username: "yosaeagd"
    ssl:
      enabled: false
    virtual-host: "yosaeagd"
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 3
        prefetch: 10
        default-requeue-rejected: true
        retry:
          enabled: true
          initial-interval: 1000ms
          max-interval: 10000ms
          max-retries: 3
          multiplier: 2



jwt:
  secret: ${JWT_SECRET_BASE64}

chirp:
  email:
    from: "empire.digipre@gmail.com"
    verification:
      expiry-hours: 24
    reset-password:
      expiry-minutes: 30


nginx:
  trusted-ips:
    - "127.0.0.1"  #nginx on same machine
    - "::1"        # IPv6 localhost
    - "172.17.0.0/16" # nginx container IP when using Docker
    - "10.0.0.5/32" # nginx server IP ( if separate machine )


supabase:
  url: "aws-1-eu-central-1.pooler.supabase.com"
  service-key: ${SUPERBASE_SERVICE_KEY}