spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.mailgun.org
    username: chirp@sandbox9c631478e492462da118b1adfbc80b26.mailgun.org


jwt:
  expiration-minutes: 1000

nginx:
  require-proxy: true

chirp:
  email:
    url: "https://pl_coding.com"
  rate-limiting:
    ip:
      apply-limit: true

  web-socket:
    allowed-origins:
     - "http://localhost:8080"